#!/bin/bash
git add . #komanda "uzmanāmo" mapju pievienošanai
git config --global user.email ak29424048@gmail.com
git config --global user.name Agusik1
git commit -m "Class_04a"
git push origin main

